version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - ./web/.env.local
    ports:
      - "3000:3000"
    depends_on:
      - api
    restart: unless-stopped