# NOTE:
# This workflow requires a Personal Access Token (PAT) with 'repo' permissions as a repository secret named RELEASE_TOKEN.
# Also, for Discord bot integration, add the following secrets:
# - DISCORD_BOT_TOKEN
# - DISCORD_CLIENT_ID
# - DISCORD_PUBLIC_KEY
# - DISCORD_CLIENT_SECRET
# NEVER commit secrets directly into workflow files or source code!

name: Create Release ZIP

on:
  release:
    types: [published]

jobs:
  package-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare clean release folder
        run: |
          mkdir release
          cp README.md release/ || true
          cp LICENSE release/ || true
          cp logo-visiotec.svg release/ || true
          cp icon-visiotec.svg release/ || true
          # Update the next line if your executable has a different name or is in another folder:
          cp visiotec.exe release/ || true
          # Add additional binaries or files as needed, e.g.:
          # cp another-binary.exe release/
          cd release
          zip -r ../${{ github.event.release.tag_name }}.zip ./*
          cd ..

      - name: Upload ZIP as release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.event.release.tag_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      # Example: Set Discord environment variables for later steps or actions if needed
      # - name: Set up Discord secrets (if needed by your workflow)
      #   run: echo "Discord secrets loaded"
      #   env:
      #     DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      #     DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      #     DISCORD_PUBLIC_KEY: ${{ secrets.DISCORD_PUBLIC_KEY }}
      #     DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
