name: Deploy Web UI to Netlify

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/deploy-web-netlify.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: ./web
          production-deploy: true
          deploy-message: "Web UI auto-deploy from GitHub Actions"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}